var collectionItemTemplate = 
   '<div class='collection-album-container column fourth'>'
+      '<img src='assets/imags/album_covers/01.png'/>'
+        '<div class='collection-album-info caption'>'
+           '<p>'
+               '<a class='album-name' href='album.html'>The                          Colors</a>'
+                '<br/>' 
+                '<a href='album.html'>Palo Picasso </a>'
+                '<br/>'
+                'X songs'
+                '<br/>'
+            '</p>'
+        '</div>'
+    '</div>'  

